export const journeyStops = [
  {
    id: "intro",
    at: 0,
    position: [112, 100, 142],
    target: [8, 0, -2],
    fov: 36,
    name: "FADO ECOSYSTEM",
    eyebrow: "FADO / VẬN HÀNH THÔNG MINH",
    title: "VẬN HÀNH<br>RÕ RÀNG.<br><em>ĐÚNG NHỊP.</em>",
    description: "Một hành trình xuyên suốt hệ sinh thái vận hành của FADO Group.",
  },
  {
    id: "hq",
    at: 0.1,
    position: [-3, 24, 45],
    target: [-30, 6, 14],
    fov: 38,
    name: "FADO GROUP HQ",
    eyebrow: "01 / TRUNG TÂM ĐIỀU PHỐI",
    title: "TẦM NHÌN<br><em>TẬP TRUNG.</em>",
    description: "Điểm khởi đầu của dữ liệu, chiến lược và điều hành toàn hệ sinh thái.",
  },
  {
    id: "commerce",
    at: 0.21,
    position: [28, 14, 4],
    target: [8, 2.8, -18],
    fov: 39,
    name: "FADO COMMERCE",
    eyebrow: "02 / THƯƠNG MẠI ĐIỆN TỬ",
    title: "GIAO DỊCH<br><em>LIỀN MẠCH.</em>",
    description: "Kết nối nhu cầu thị trường với dữ liệu và năng lực vận hành tập trung.",
  },
  {
    id: "digital",
    at: 0.31,
    position: [19, 13, 18],
    target: [4, 2.2, 0],
    fov: 41,
    name: "FADO DIGITAL",
    eyebrow: "03 / HẠ TẦNG SỐ",
    title: "DỮ LIỆU<br><em>CHUYỂN ĐỘNG.</em>",
    description: "Nền tảng số liên kết các điểm chạm thương mại trong cùng một luồng.",
  },
  {
    id: "technology",
    at: 0.4,
    position: [2, 14, 18],
    target: [-11, 2.4, 4],
    fov: 40,
    name: "FADO TECHNOLOGY",
    eyebrow: "04 / CÔNG NGHỆ VẬN HÀNH",
    title: "CÔNG NGHỆ<br><em>TẠO NHỊP.</em>",
    description: "Hạ tầng công nghệ giúp hệ sinh thái quan sát, kết nối và phản hồi nhanh.",
  },
  {
    id: "fulfillment",
    at: 0.5,
    position: [-4, 16, 6],
    target: [-26, 3, -16],
    fov: 39,
    name: "FADO FULFILLMENT",
    eyebrow: "05 / HOÀN TẤT ĐƠN HÀNG",
    title: "PHÂN PHỐI<br><em>CÓ TRẬT TỰ.</em>",
    description: "Kho hàng, bến nhận và luồng phương tiện phối hợp quanh một trung tâm.",
  },
  {
    id: "logistics",
    at: 0.61,
    position: [25, 13, 32],
    target: [8, 3, 14],
    fov: 38,
    name: "FADO LOGISTICS",
    eyebrow: "06 / ĐIỀU PHỐI LUỒNG HÀNG",
    title: "KẾT NỐI<br><em>NHIỀU ĐIỂM CHẠM.</em>",
    description: "Các tuyến vận hành hội tụ trước khi hàng hóa đi tới mạng lưới toàn cầu.",
  },
  {
    id: "port",
    at: 0.71,
    position: [64, 18, 54],
    target: [39, 5, 33],
    fov: 41,
    name: "PROSHIP LOGISTICS",
    eyebrow: "07 / VẬN TẢI QUỐC TẾ",
    title: "VƯƠN RA<br><em>THẾ GIỚI.</em>",
    description: "Container, cần cẩu và tàu hàng tạo thành cửa ngõ vận tải quốc tế.",
  },
  {
    id: "airport",
    at: 0.81,
    position: [56, 21, -69],
    target: [17, 2.2, -47],
    fov: 42,
    name: "GLOBAL DELIVERY",
    eyebrow: "08 / KẾT NỐI HÀNG KHÔNG",
    title: "GIAO NHẬN<br><em>KHÔNG BIÊN GIỚI.</em>",
    description: "Chặng cuối mở rộng hệ sinh thái từ vận hành nội bộ ra mạng lưới toàn cầu.",
  },
  {
    id: "overview",
    at: 0.91,
    position: [104, 83, 126],
    target: [4, 0, -4],
    fov: 38,
    name: "FADO GROUP",
    eyebrow: "09 / HỆ SINH THÁI KẾT NỐI",
    title: "DỮ LIỆU.<br>QUY TRÌNH.<br><em>HÀNH ĐỘNG.</em>",
    description: "Một hệ sinh thái doanh nghiệp được kết nối trong cùng một góc nhìn.",
  },
];
